FROM ubuntu:20.04

RUN mkdir /app
WORKDIR /app
COPY * /app/

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y
RUN apt-get install -y \
    build-essential \
    libcurl4-openssl-dev \
    libjsoncpp-dev \
    libboost-all-dev \
    nlohmann-json3-dev \
    cmake \
    wget \
    git

# Install the Azure Guest Attestation package
RUN wget https://packages.microsoft.com/repos/azurecore/pool/main/a/azguestattestation1/azguestattestation1_1.0.5_amd64.deb
RUN dpkg -i azguestattestation1_1.0.5_amd64.deb

# Clone, build and run the AttestationClient app
RUN git clone https://github.com/Azure/confidential-computing-cvm-guest-attestation.git
RUN cd confidential-computing-cvm-guest-attestation/cvm-attestation-sample-app && cmake . && make && cp ./AttestationClient /

# Clone, build and run the AzureAttestSKR app
RUN git clone https://github.com/Azure/confidential-computing-cvm-guest-attestation.git
RUN cd confidential-computing-cvm-guest-attestation/cvm-securekey-release-app && cmake . && make && cp ./AzureAttestSKR /

RUN apt install -y python3 python3-pip

#Build Python Here
# Install pip requirements
ADD requirements.txt .
RUN python3 -m pip install -r requirements.txt

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["python3", "attestation_client.py"]